{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE TemplateHaskell #-}

-- |
-- Module      : Domain.Transaction.CommandHandler
-- Description : Command handler for the Transaction aggregate
--
-- This module implements the command handler that validates transaction commands
-- against the current aggregate state and emits appropriate events.
--
-- The command handler is the core of the write side in CQRS:
--   1. Receives a command (user intent)
--   2. Loads current state via projection
--   3. Validates command against business rules
--   4. Emits events if valid (or no events if invalid)
--
-- Key Components:
--   - TransactionCommand: Sum type of all transaction commands (generated by TH)
--   - handleTransactionCommand: Command validation logic
--   - transactionCommandHandler: CommandHandler for eventium integration
--
-- Business Rules Enforced:
--   - InitiateTransfer: Source and target must be different, amount must be positive
--   - CompleteTransfer: Can only complete transactions in Pending status
--   - FailTransfer: Can only fail transactions in Pending status
--
-- All validation is pure and deterministic - same command + state → same events.
module Domain.Transaction.CommandHandler
  ( -- * Command Sum Type
    TransactionCommand (..),

    -- * Command Errors
    TransactionError (..),

    -- * Command Handler
    transactionCommandHandler,

    -- * Handler Function (exported for testing)
    handleTransactionCommand,
  )
where

import Data.List.NonEmpty (NonEmpty)
import qualified Data.List.NonEmpty as NE
import Domain.Core.Types
  ( Allocation (..),
    Allocations,
    Currency,
    Money,
    TransferKind (..),
    TransferType (..),
    allSameCurrency,
    allocationsOf,
    categorisedAmount,
    kindOf,
    moneyCurrency,
    rescaleAllocations,
    sumAllocationsUnchecked,
    unAccountId,
    unMoney,
  )
import Domain.Transaction.Commands
import Domain.Transaction.Events
import Domain.Transaction.Projection
import Eventium (CommandHandler (..))
import Eventium.TH.SumType (SumTypeTagOptions (AppendTypeNameToTags), constructSumType, defaultSumTypeOptions, withTagOptions)
import Optics ((^.))

-- -----------------------------------------------------------------------------
-- Command Errors
-- -----------------------------------------------------------------------------

-- | Errors that can occur when handling transaction commands.
--
-- These are aggregate-local errors. The service layer translates them into
-- their 'Domain.Core.Errors.DomainError' counterparts before surfacing to
-- the HTTP layer.
data TransactionError
  = TransactionAlreadyInitiated
  | TransactionNotPending
  | TransferToSameAccount
  | TransferAmountNotPositive
  | -- | An edit command (labels, category, description, business date)
    -- was issued against a transaction whose status is not Completed.
    CannotEditUncompletedTransaction
  | -- | 'SetTransactionAllocations' issued against a Transfer or Adjustment,
    -- which has no allocations to set.
    CannotSetAllocationsOnUncategorisedTransaction
  | -- | 'SetTransactionAllocations' / 'AmendTransfer' issued with a
    -- @newTransferType@ whose kind differs from the existing transaction's.
    CannotChangeKindOfCategorisedTransaction
  | -- | Sum of allocation amounts does not equal the categorised total.
    AllocationsDoNotSumToTotal
  | -- | At least one allocation has a non-positive amount.
    AllocationAmountNotPositive
  | -- | An allocation's currency differs from the categorised side's.
    AllocationCurrencyMismatch
  | -- | AmendTransfer payload referenced the same account on both legs.
    AmendTransferToSameAccountPair
  | -- | AmendTransfer payload carried a zero source or target amount.
    AmendTransferToZeroAmount
  | -- | A saga-completion or saga-failure command was issued without
    -- a prior 'TransferAmendmentInitiated' on the stream.
    NoAmendmentInProgress
  | -- | 'CancelTransaction' was issued against a transaction that is already
    -- in the 'Cancelled' state.
    TransactionAlreadyCancelled
  | -- | 'CancelTransaction' was issued while a cancellation saga is already
    -- in flight (@cancellationInProgress = True@).
    CancellationAlreadyInProgress
  | -- | 'CancelTransaction' was issued while an amendment saga is in flight
    -- (@amendmentInProgress = True@). The amendment must complete or fail
    -- first.
    CannotCancelDuringAmendment
  | -- | 'CompleteTransactionCancellation' was issued when no cancellation is
    -- in progress (@cancellationInProgress = False@).
    NoCancellationInProgress
  | -- | 'AmendTransfer' was issued while a cancellation saga is in flight
    -- (@cancellationInProgress = True@).
    CannotAmendDuringCancellation
  deriving (Show, Eq)

-- -----------------------------------------------------------------------------
-- Command Sum Type Construction
-- -----------------------------------------------------------------------------

-- | Generate the TransactionCommand sum type from individual command types.
--
-- This Template Haskell splice creates:
--  data TransactionCommand
--    = InitiateTransferTransactionCommand InitiateTransfer
--    | CompleteTransferTransactionCommand CompleteTransfer
--    | FailTransferTransactionCommand FailTransfer
--
-- Each variant wraps one of the individual command types defined in
-- Domain.Transaction.Commands.
--
-- The sum type enables pattern matching on all possible commands in the
-- handler function.
constructSumType
  "TransactionCommand"
  (withTagOptions AppendTypeNameToTags defaultSumTypeOptions)
  transactionCommands

-- -----------------------------------------------------------------------------
-- Command Handler Function
-- -----------------------------------------------------------------------------

-- | Handle a transaction command and produce events.
--
-- This function implements the business logic for validating commands against
-- the current aggregate state. It is pure and deterministic.
--
-- Command Handling:
--  - InitiateTransfer: Validates accounts differ, amount positive, emits TransferInitiated
--  - CompleteTransfer: Validates status is Pending, emits TransferCompleted
--  - FailTransfer: Validates status is Pending, emits TransferFailed
--
-- Business Rules:
--  1. InitiateTransfer can only be first command (status must not be set)
--  2. Source and target accounts must be different
--  3. Transfer amount must be positive
--  4. CompleteTransfer only works on Pending transactions
--  5. FailTransfer only works on Pending transactions
--  6. Terminal states (Completed/Failed) cannot be modified
--
-- Returns:
--  @'Right' events@ on success, @'Left' error@ on rejection.
--
-- Mathematical Property:
--  handleTransactionCommand is deterministic:
--  ∀ s c. handleTransactionCommand s c == handleTransactionCommand s c
--
-- State Machine Enforcement:
--  Only Pending transactions can transition to Completed or Failed.
handleTransactionCommand :: Transaction -> TransactionCommand -> Either TransactionError [TransactionEvent]
-- Handle InitiateTransfer command
handleTransactionCommand transaction (InitiateTransferTransactionCommand InitiateTransfer {..}) =
  case transaction ^. #status of
    Pending
      | unMoney transaction.sourceAmount == 0 ->
          if unAccountId sourceAccountId == unAccountId targetAccountId
            then Left TransferToSameAccount
            else
              if unMoney sourceAmount <= 0 || unMoney targetAmount <= 0
                then Left TransferAmountNotPositive
                else do
                  -- Categorised-side checks. Smart constructors should have
                  -- run these, but we re-check defensively at the handler
                  -- boundary because nothing prevents a caller from
                  -- assembling a 'TransferType' directly.
                  case transferType of
                    Income allocs -> checkAllocationsAgainst targetAmount allocs
                    Expense allocs -> checkAllocationsAgainst sourceAmount allocs
                    Transfer -> Right ()
                    Adjustment -> Right ()
                  Right
                    [ TransferInitiatedTransactionEvent
                        TransferInitiated
                          { sourceAccountId = sourceAccountId,
                            targetAccountId = targetAccountId,
                            sourceAmount = sourceAmount,
                            targetAmount = targetAmount,
                            exchangeRate = exchangeRate,
                            description = description,
                            by = initiatedBy,
                            at = at,
                            transferType = transferType,
                            externalTransactionId = externalTransactionId,
                            labels = labels
                          }
                    ]
      | otherwise -> Left TransactionAlreadyInitiated
    _ -> Left TransactionAlreadyInitiated
-- Handle CompleteTransfer command
handleTransactionCommand transaction (CompleteTransferTransactionCommand CompleteTransfer) =
  case transaction ^. #status of
    Pending -> Right [TransferCompletedTransactionEvent TransferCompleted]
    _ -> Left TransactionNotPending
-- Handle FailTransfer command
handleTransactionCommand transaction (FailTransferTransactionCommand FailTransfer {..}) =
  case transaction ^. #status of
    Pending ->
      Right
        [ TransferFailedTransactionEvent
            TransferFailed
              { reason = reason
              }
        ]
    _ -> Left TransactionNotPending
-- Handle SetTransactionLabels command
handleTransactionCommand transaction (SetTransactionLabelsTransactionCommand SetTransactionLabels {..}) =
  case transaction ^. #status of
    Completed ->
      Right
        [ TransactionLabelsSetTransactionEvent
            TransactionLabelsSet
              { transactionId = transactionId,
                labels = labels
              }
        ]
    _ -> Left CannotEditUncompletedTransaction
-- Handle SetTransactionAllocations command
--
-- The command carries only the new allocation list; the surrounding
-- kind (Income / Expense) is preserved from the existing transaction.
-- Kind preservation is therefore structural — there is no incoming
-- kind to compare with — so we only check that the existing
-- transaction is categorised, then validate the allocations against
-- the existing categorised total / currency / positivity.
handleTransactionCommand transaction (SetTransactionAllocationsTransactionCommand SetTransactionAllocations {..}) =
  case transaction ^. #status of
    Completed ->
      case allocationsOf (transaction ^. #transferType) of
        Nothing ->
          Left CannotSetAllocationsOnUncategorisedTransaction
        Just existingAllocs -> do
          let existingTotal = sumAllocationsUnchecked existingAllocs
          checkAllocationsAgainst existingTotal newAllocations
          Right
            [ TransactionAllocationsChangedTransactionEvent
                TransactionAllocationsChanged
                  { transactionId = transactionId,
                    newAllocations = newAllocations
                  }
            ]
    _ -> Left CannotEditUncompletedTransaction
-- Handle ChangeTransactionDescription command
handleTransactionCommand transaction (ChangeTransactionDescriptionTransactionCommand ChangeTransactionDescription {..}) =
  case transaction ^. #status of
    Completed ->
      Right
        [ TransactionDescriptionChangedTransactionEvent
            TransactionDescriptionChanged
              { transactionId = transactionId,
                newDescription = newDescription
              }
        ]
    _ -> Left CannotEditUncompletedTransaction
-- Handle ChangeTransactionDate command
handleTransactionCommand transaction (ChangeTransactionDateTransactionCommand ChangeTransactionDate {..}) =
  case transaction ^. #status of
    Completed ->
      Right
        [ TransactionDateChangedTransactionEvent
            TransactionDateChanged
              { transactionId = transactionId,
                newAt = newAt
              }
        ]
    _ -> Left CannotEditUncompletedTransaction
-- Handle AmendTransfer command
handleTransactionCommand transaction (AmendTransferTransactionCommand AmendTransfer {..}) =
  case transaction ^. #status of
    Completed
      | transaction ^. #cancellationInProgress ->
          Left CannotAmendDuringCancellation
      | unAccountId newSourceAccountId == unAccountId newTargetAccountId ->
          Left AmendTransferToSameAccountPair
      | unMoney newSourceAmount == 0 || unMoney newTargetAmount == 0 ->
          Left AmendTransferToZeroAmount
      | otherwise ->
          Right
            [ TransferAmendmentInitiatedTransactionEvent
                TransferAmendmentInitiated
                  { transactionId = transactionId,
                    newSourceAccountId = newSourceAccountId,
                    newTargetAccountId = newTargetAccountId,
                    newSourceAmount = newSourceAmount,
                    newTargetAmount = newTargetAmount,
                    newExchangeRate = newExchangeRate,
                    amendedBy = amendedBy
                  }
            ]
    _ -> Left CannotEditUncompletedTransaction
-- Handle CompleteTransferAmendment command
--
-- The handler computes the post-amendment allocations once and emits
-- them on the event. Projections apply 'evt.newAllocations' via
-- 'replaceAllocations' on the existing kind. The command itself is
-- lean (posting facts only); the scaled allocations are a
-- handler-computed fact, not a user-amendable input.
--
-- For categorised existing kinds (Income / Expense) the field is
-- 'Just' (rescaled when the categorised amount changed, verbatim
-- otherwise). For 'Transfer' / 'Adjustment' the field is 'Nothing'.
handleTransactionCommand transaction (CompleteTransferAmendmentTransactionCommand CompleteTransferAmendment {..}) =
  if not (transaction ^. #amendmentInProgress)
    then Left NoAmendmentInProgress
    else
      let oldTransferType = transaction ^. #transferType
          scaledAllocations :: Maybe Allocations
          scaledAllocations = case (kindOf oldTransferType, allocationsOf oldTransferType) of
            (IncomeKind, Just oldAllocs) ->
              -- Income's categorised side = target amount.
              let oldTotal = sumAllocationsUnchecked oldAllocs
               in Just $
                    if oldTotal /= newTargetAmount
                      then rescaleAllocations oldTotal newTargetAmount oldAllocs
                      else oldAllocs
            (ExpenseKind, Just oldAllocs) ->
              -- Expense's categorised side = source amount.
              let oldTotal = sumAllocationsUnchecked oldAllocs
               in Just $
                    if oldTotal /= newSourceAmount
                      then rescaleAllocations oldTotal newSourceAmount oldAllocs
                      else oldAllocs
            _ -> Nothing
       in Right
            [ TransferAmendmentCompletedTransactionEvent
                TransferAmendmentCompleted
                  { transactionId = transactionId,
                    newSourceAccountId = newSourceAccountId,
                    newTargetAccountId = newTargetAccountId,
                    newSourceAmount = newSourceAmount,
                    newTargetAmount = newTargetAmount,
                    newExchangeRate = newExchangeRate,
                    newAllocations = scaledAllocations,
                    amendedBy = amendedBy
                  }
            ]
-- Handle FailTransferAmendment command
handleTransactionCommand transaction (FailTransferAmendmentTransactionCommand FailTransferAmendment {..}) =
  if not (transaction ^. #amendmentInProgress)
    then Left NoAmendmentInProgress
    else
      Right
        [ TransferAmendmentFailedTransactionEvent
            TransferAmendmentFailed
              { reason = reason
              }
        ]
-- Handle CancelTransaction command
handleTransactionCommand transaction (CancelTransactionTransactionCommand CancelTransaction {..}) =
  case transaction ^. #status of
    Completed
      | transaction ^. #amendmentInProgress -> Left CannotCancelDuringAmendment
      | transaction ^. #cancellationInProgress -> Left CancellationAlreadyInProgress
      | otherwise ->
          Right
            [ TransactionCancellationInitiatedTransactionEvent
                TransactionCancellationInitiated
                  { transactionId = transactionId,
                    cancelledBy = cancelledBy
                  }
            ]
    Cancelled -> Left TransactionAlreadyCancelled
    _ -> Left CannotEditUncompletedTransaction
-- Handle CompleteTransactionCancellation command
handleTransactionCommand transaction (CompleteTransactionCancellationTransactionCommand CompleteTransactionCancellation {..}) =
  if not (transaction ^. #cancellationInProgress)
    then Left NoCancellationInProgress
    else
      Right
        [ TransactionCancellationCompletedTransactionEvent
            TransactionCancellationCompleted
              { transactionId = transactionId,
                cancelledBy = cancelledBy
              }
        ]

-- -----------------------------------------------------------------------------
-- Allocation invariants (handler-boundary)
-- -----------------------------------------------------------------------------

-- | Check that an allocation list is consistent with the expected total:
-- currency equality, sum equality, and per-allocation positivity. Used by
-- 'InitiateTransfer', 'SetTransactionAllocations', and 'AmendTransfer'
-- handler arms as a defensive boundary check (the smart constructors in
-- 'Domain.Core.Types' already enforce these — the re-check covers
-- direct constructions bypassing them).
checkAllocationsAgainst :: Money -> Allocations -> Either TransactionError ()
checkAllocationsAgainst expected allocs =
  checkCurrency *> checkSum *> checkPositive
  where
    expectedCurrency :: Currency
    expectedCurrency = moneyCurrency expected

    checkCurrency :: Either TransactionError ()
    checkCurrency =
      if allSameCurrency expectedCurrency allocs
        then Right ()
        else Left AllocationCurrencyMismatch

    checkSum :: Either TransactionError ()
    checkSum =
      if sumAllocationsUnchecked allocs == expected
        then Right ()
        else Left AllocationsDoNotSumToTotal

    checkPositive :: Either TransactionError ()
    checkPositive = case NE.filter (\(Allocation _ m) -> unMoney m <= 0) allocs of
      [] -> Right ()
      _ -> Left AllocationAmountNotPositive

-- -----------------------------------------------------------------------------
-- Command Handler
-- -----------------------------------------------------------------------------

-- | The transaction command handler for eventium integration.
--
-- This combines the command handler function with the transaction projection,
-- creating a complete CommandHandler that can be registered with eventium's
-- event store.
--
-- The CommandHandler type provides:
--  - commandHandlerHandler: The validation function (handleTransactionCommand)
--  - commandHandlerProjection: How to rebuild state (transactionProjection)
--
-- Usage with eventium:
-- >>> applyCommandHandler writer reader transactionCommandHandler transactionId command
--
-- The command handler will:
--  1. Load current state via transactionProjection
--  2. Validate command via handleTransactionCommand
--  3. Store emitted events in event store
--  4. Return the events that were stored
--
-- Properties:
--  - Deterministic: Same command + state → same events
--  - Pure: No side effects in validation logic
--  - Composable: Can be combined with other command handlers
--  - State Machine: Enforces valid status transitions
--
-- Usage in Process Manager:
--  The process manager will use this command handler to issue CompleteTransfer
--  and FailTransfer commands based on the outcome of account operations.
transactionCommandHandler :: CommandHandler Transaction TransactionEvent TransactionCommand TransactionError
transactionCommandHandler = CommandHandler handleTransactionCommand transactionProjection
