{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE TemplateHaskell #-}

-- |
-- Module      : Domain.Transaction.Projection
-- Description : Projection for rebuilding Transaction aggregate state from events
--
-- This module defines the Transaction aggregate state and how it is reconstructed
-- from the event stream. The projection implements event sourcing by folding
-- events over an initial state to produce the current state.
--
-- Key Components:
--   - Transaction: The aggregate state containing transfer details and status
--   - TransactionEvent: Sum type of all possible transaction events (generated by TH)
--   - transactionProjection: The projection that rebuilds state from events
--
-- The projection is the core of event sourcing - it ensures that the current
-- state can always be reconstructed by replaying the event history.
--
-- Mathematical Properties:
--   - Deterministic: Same events always produce same state
--   - Associative: Order of event application matters
--   - Idempotent event handlers: Replaying same events produces same result
--   - Status transitions: Pending → Completed | Failed (terminal states)
module Domain.Transaction.Projection
  ( -- * Transaction Aggregate
    Transaction (..),

    -- * Transaction Status
    TransactionStatus (..),
    StatusKind (..),
    statusKind,
    parseStatusKind,
    renderStatusKind,

    -- * Optics Labels (via OverloadedLabels)
    -- $labels

    -- * Event Sum Type
    TransactionEvent (..),

    -- * Projection
    transactionProjection,

    -- * Helper Functions
    transactionDefault,
  )
where

import Data.Aeson (FromJSON, ToJSON)
import Data.Aeson.TH (defaultOptions, deriveJSON)
import qualified Data.List.NonEmpty as NE
import Data.Set (Set)
import qualified Data.Set as Set
import Data.Text (Text)
import qualified Data.Text as T
import Data.Time (UTCTime (..), fromGregorian)
import Data.UUID (nil)
import Domain.Core.Types (AccountId, ExchangeRate, LabelId, Money, TransactionType, UserId, mkAccountId, mkAllocation, mkDefaultMoney, mkIncome, replaceAllocations, unsafeDictionaryEntryId, unsafeUserId)
import Domain.Transaction.Events
import Eventium (Projection (..))
import Eventium.TH.SumType (SumTypeTagOptions (AppendTypeNameToTags), constructSumType, defaultSumTypeOptions, withTagOptions)
import GHC.Generics (Generic)
import Optics (makeFieldLabelsNoPrefix, (%~), (&), (.~), (^.))

-- -----------------------------------------------------------------------------
-- Transaction Status
-- -----------------------------------------------------------------------------

-- | The status of a transaction in its lifecycle.
--
-- A transaction progresses through states:
--  - Pending: Transfer initiated but not yet completed
--  - Completed: Transfer successfully finished
--  - Failed: Transfer failed and cannot be completed
--
-- State Transitions:
--  Pending → Completed (via TransactionPostingCompleted event)
--  Pending → Failed (via TransactionPostingFailed event)
--
-- Terminal States: Completed and Failed are final states with no further transitions.
--
-- Invariant: Once a transaction reaches Completed, Failed, or Cancelled, its status cannot change.
data TransactionStatus
  = -- | Transaction is in progress
    Pending
  | -- | Transaction completed successfully
    Completed
  | -- | Transaction failed with a reason
    Failed Text
  | -- | Transaction was cancelled by the user
    Cancelled
  deriving (Show, Eq, Generic)

instance ToJSON TransactionStatus

instance FromJSON TransactionStatus

-- | Payload-free discriminator of 'TransactionStatus', used by query
-- filters. Unlike 'TransactionStatus' it carries no @Failed@ reason, so the
-- query layer never depends on write-side failure detail.
data StatusKind = PendingKind | CompletedKind | FailedKind | CancelledKind
  deriving (Show, Eq, Ord, Enum, Bounded, Generic)

-- | Project a 'TransactionStatus' onto its 'StatusKind'.
statusKind :: TransactionStatus -> StatusKind
statusKind Pending = PendingKind
statusKind Completed = CompletedKind
statusKind (Failed _) = FailedKind
statusKind Cancelled = CancelledKind

-- | Render a 'StatusKind' to its lowercase wire token.
renderStatusKind :: StatusKind -> Text
renderStatusKind PendingKind = "pending"
renderStatusKind CompletedKind = "completed"
renderStatusKind FailedKind = "failed"
renderStatusKind CancelledKind = "cancelled"

-- | Parse a wire token (trimmed, case-insensitive) to a 'StatusKind'.
parseStatusKind :: Text -> Maybe StatusKind
parseStatusKind raw = case T.toLower (T.strip raw) of
  "pending" -> Just PendingKind
  "completed" -> Just CompletedKind
  "failed" -> Just FailedKind
  "cancelled" -> Just CancelledKind
  _ -> Nothing

-- -----------------------------------------------------------------------------
-- Transaction Aggregate State
-- -----------------------------------------------------------------------------

-- | The Transaction aggregate state.
--
-- This represents the current state of a money transfer transaction, reconstructed
-- from its event history. The state is immutable and can only be changed by
-- applying events through the projection.
--
-- Fields:
--   - sourceAccountId: Source account for the transfer
--   - targetAccountId: Destination account for the transfer
--   - amount: Amount being transferred
--   - description: Description/reason for the transfer
--   - status: Current status (Pending, Completed, Failed)
--   - initiatedBy: User who initiated the transfer (for audit trail)
--
-- Invariants:
--   - Amount is always non-negative (enforced by Money type)
--   - Status transitions are unidirectional (Pending → terminal state)
--   - Source and target accounts should be different (validated at command level)
--   - State can only be modified through event handlers
--
-- State Machine:
--   Pending -[TransactionPostingCompleted]-> Completed
--   Pending -[TransactionPostingFailed]-> Failed
--
-- Example:
-- >>> let tx = Transaction sourceId targetId (Money 500.0) (Money 500.0) Nothing "Rent" Pending userId
-- >>> tx ^. #status
-- Pending
data Transaction = Transaction
  { -- | Account from which money is being debited
    sourceAccountId :: AccountId,
    -- | Account to which money is being credited
    targetAccountId :: AccountId,
    -- | Amount debited from source account
    sourceAmount :: Money,
    -- | Amount credited to target account
    targetAmount :: Money,
    -- | Exchange rate used (Nothing if same-currency)
    exchangeRate :: Maybe ExchangeRate,
    -- | Description of the transfer
    description :: Text,
    -- | Business date / time of the transfer, replayed from
    -- 'TransactionPostingInitiated' and mutated by 'TransactionDateChanged'.
    at :: UTCTime,
    -- | Current status of the transaction
    status :: TransactionStatus,
    -- | User who initiated the transfer
    initiatedBy :: UserId,
    -- | Type of transfer (Income, Expense, Transfer)
    transactionType :: TransactionType,
    -- | Labels attached to this transaction (may be empty).
    labels :: Set LabelId,
    -- | Count of 'TransactionAmendmentCompleted' events folded so far.
    -- Exposed on the API surface so clients can detect amendments and
    -- fetch the audit history if interested. Always @0@ on a transaction
    -- that has never been amended.
    amendmentCount :: Word,
    -- | Transient flag: True when a 'TransactionAmendmentInitiated' event has
    -- been applied but a corresponding 'TransactionAmendmentCompleted' or
    -- 'TransactionAmendmentFailed' has not yet arrived. Used by the command
    -- handler to gate 'CompleteTransactionAmendment' and 'FailTransactionAmendment'.
    amendmentInProgress :: Bool,
    -- | Transient flag: True when a 'TransactionCancellationInitiated' event has
    -- been applied but a corresponding 'TransactionCancellationCompleted' has not
    -- yet arrived. Used by the command handler to gate 'CompleteTransactionCancellation'.
    cancellationInProgress :: Bool
  }
  deriving (Show, Eq)

-- Generate optics labels for Transaction fields (accessed via #fieldName)
makeFieldLabelsNoPrefix ''Transaction

-- Derive JSON instances for Transaction (fields already unprefixed)
deriveJSON defaultOptions ''Transaction

-- | Default initial state for a Transaction aggregate.
--
-- This represents an uninitialized transaction before the TransactionPostingInitiated event
-- has been applied. It serves as the seed for the projection.
--
-- Note: In practice, this state should never be observed directly, as the
-- first event in any transaction stream should be TransactionPostingInitiated.
--
-- We use dummy values that will be overwritten by the first event:
--   - Empty UUIDs for account IDs and user ID (will be set by TransactionPostingInitiated)
--   - Zero amount (will be set by TransactionPostingInitiated)
--   - Empty description (will be set by TransactionPostingInitiated)
--   - Pending status (initial status)
-- | Sentinel 'TransactionType' used by 'transactionDefault'. Only observed
-- before the first event is applied; 'TransactionPostingInitiated' overwrites the
-- entire 'transactionType' on the aggregate. The placeholder uses a unit
-- USD amount because the smart constructor rejects zero or negative
-- magnitudes.
defaultTransactionType :: TransactionType
defaultTransactionType =
  case mkIncome placeholderUnit (NE.singleton placeholderAlloc) of
    Right tt -> tt
    Left err -> error ("transactionDefault: mkIncome should never fail: " <> show err)
  where
    placeholderUnit = case mkDefaultMoney 1 of
      Right m -> m
      Left _ -> error "transactionDefault: mkDefaultMoney 1 should never fail"
    placeholderAlloc =
      case mkAllocation (unsafeDictionaryEntryId nil) placeholderUnit of
        Right a -> a
        Left err -> error ("transactionDefault: mkAllocation should never fail: " <> show err)

transactionDefault :: Transaction
transactionDefault =
  Transaction
    { sourceAccountId = case mkAccountId nil of
        Right aid -> aid
        Left _ -> error "transactionDefault: mkAccountId should never fail for nil UUID",
      targetAccountId = case mkAccountId nil of
        Right aid -> aid
        Left _ -> error "transactionDefault: mkAccountId should never fail for nil UUID",
      sourceAmount = case mkDefaultMoney 0 of
        Right m -> m
        Left _ -> error "transactionDefault: mkDefaultMoney 0 should never fail",
      targetAmount = case mkDefaultMoney 0 of
        Right m -> m
        Left _ -> error "transactionDefault: mkDefaultMoney 0 should never fail",
      exchangeRate = Nothing,
      description = "",
      at = UTCTime (fromGregorian 1970 1 1) 0,
      status = Pending,
      initiatedBy = unsafeUserId nil,
      transactionType = defaultTransactionType,
      labels = Set.empty,
      amendmentCount = 0,
      amendmentInProgress = False,
      cancellationInProgress = False
    }

-- -----------------------------------------------------------------------------
-- Event Sum Type Construction
-- -----------------------------------------------------------------------------

-- | Generate the TransactionEvent sum type from individual event types.
--
-- This Template Haskell splice creates:
--  data TransactionEvent
--    = TransactionPostingInitiatedTransactionEvent TransactionPostingInitiated
--    | TransactionPostingCompletedTransactionEvent TransactionPostingCompleted
--    | TransactionPostingFailedTransactionEvent TransactionPostingFailed
--
-- Each variant wraps one of the individual event types defined in
-- Domain.Transaction.Events.
constructSumType
  "TransactionEvent"
  (withTagOptions AppendTypeNameToTags defaultSumTypeOptions)
  transactionEvents

-- Derive Show and Eq instances for the generated TransactionEvent type
deriving instance Show TransactionEvent

deriving instance Eq TransactionEvent

-- -----------------------------------------------------------------------------
-- Event Handlers
-- -----------------------------------------------------------------------------

-- | Handle an event and update the transaction state.
--
-- This function implements the business logic for how each event affects
-- the transaction state. It is pure and deterministic - the same event applied
-- to the same state always produces the same result.
--
-- Event Handling:
--  - TransactionPostingInitiated: Initialize transaction with accounts, amount, description, and Pending status
--  - TransactionPostingCompleted: Update status to Completed (terminal state)
--  - TransactionPostingFailed: Update status to Failed with reason (terminal state)
--
-- State Transition Rules:
--  - TransactionPostingInitiated can only be applied to default/uninitialized state
--  - TransactionPostingCompleted can only be applied to Pending transactions
--  - TransactionPostingFailed can only be applied to Pending transactions
--  - No events can modify Completed or Failed transactions (idempotent)
--
-- Mathematical Property:
--  forall e1 e2 s. handleTransactionEvent (handleTransactionEvent s e1) e2
--                   == handleTransactionEvent s (e1 <> e2)
--
-- where (<>) represents event sequencing.
--
-- Note: The function is total and handles all possible events, even if they
-- represent invalid state transitions (e.g., completing an already completed
-- transaction). In such cases, the state remains unchanged (idempotent).
handleTransactionEvent :: Transaction -> TransactionEvent -> Transaction
handleTransactionEvent transaction (TransactionPostingInitiatedTransactionEvent evt) =
  -- Initialize a new transaction with transfer details
  transaction
    & #sourceAccountId
    .~ evt.sourceAccountId
    & #targetAccountId
    .~ evt.targetAccountId
    & #sourceAmount
    .~ evt.sourceAmount
    & #targetAmount
    .~ evt.targetAmount
    & #exchangeRate
    .~ evt.exchangeRate
    & #description
    .~ evt.description
    & #at
    .~ evt.at
    & #status
    .~ Pending
    & #initiatedBy
    .~ evt.by
    & #transactionType
    .~ evt.transactionType
    & #labels
    .~ evt.labels
handleTransactionEvent transaction (TransactionPostingCompletedTransactionEvent TransactionPostingCompleted) =
  -- Mark transaction as completed
  -- Only update if currently Pending (idempotent for other states)
  case transaction ^. #status of
    Pending -> transaction & #status .~ Completed
    _ -> transaction -- Already in terminal state, no change
handleTransactionEvent transaction (TransactionPostingFailedTransactionEvent evt) =
  -- Mark transaction as failed with reason
  -- Only update if currently Pending (idempotent for other states)
  case transaction ^. #status of
    Pending -> transaction & #status .~ Failed evt.reason
    _ -> transaction -- Already in terminal state, no change
handleTransactionEvent transaction (TransactionLabelsSetTransactionEvent evt) =
  -- Replace the label set. Valid only against Completed; treated as a
  -- no-op in other states for defensive robustness — the command handler
  -- is authoritative on well-formed streams.
  case transaction ^. #status of
    Completed -> transaction & #labels .~ evt.labels
    _ -> transaction
handleTransactionEvent transaction (TransactionAllocationsChangedTransactionEvent evt) =
  -- The event carries only the new allocations; the kind (Income /
  -- Expense) is preserved structurally — the command handler rejects
  -- the command against uncategorised aggregates. 'replaceAllocations'
  -- rebuilds the full 'TransactionType' from the existing kind.
  transaction & #transactionType .~ replaceAllocations evt.newAllocations (transaction ^. #transactionType)
handleTransactionEvent transaction (TransactionDescriptionChangedTransactionEvent evt) =
  -- Replace the description. The command handler enforces Completed-only;
  -- the projection itself is permissive.
  transaction & #description .~ evt.newDescription
handleTransactionEvent transaction (TransactionDateChangedTransactionEvent evt) =
  -- Replace the business date. The command handler enforces Completed-only;
  -- the projection itself is permissive.
  transaction & #at .~ evt.newAt
handleTransactionEvent transaction (TransactionAmendmentInitiatedTransactionEvent _evt) =
  -- Flip the transient saga-in-progress flag on so the command handler
  -- can gate CompleteTransactionAmendment / FailTransactionAmendment.
  -- Canonical posting fields are unchanged until TransactionAmendmentCompleted.
  transaction & #amendmentInProgress .~ True
handleTransactionEvent transaction (TransactionAmendmentCompletedTransactionEvent evt) =
  -- Replace canonical posting facts with the amended values; write the
  -- synthesised 'newTransactionType' verbatim; bump the amendment count;
  -- clear the saga-in-progress flag.
  transaction
    & #sourceAccountId
    .~ evt.newSourceAccountId
    & #targetAccountId
    .~ evt.newTargetAccountId
    & #sourceAmount
    .~ evt.newSourceAmount
    & #targetAmount
    .~ evt.newTargetAmount
    & #exchangeRate
    .~ evt.newExchangeRate
    & #transactionType
    .~ evt.newTransactionType
    & #amendmentCount
    %~ (+ 1)
    & #amendmentInProgress
    .~ False
handleTransactionEvent transaction (TransactionAmendmentFailedTransactionEvent _evt) =
  -- Clear the in-progress flag. No canonical change on failure.
  transaction & #amendmentInProgress .~ False
handleTransactionEvent transaction (TransactionCancellationInitiatedTransactionEvent _) =
  -- Flip the transient saga-in-progress flag on so the command handler
  -- can gate 'CompleteTransactionCancellation'. Canonical status is
  -- unchanged until 'TransactionCancellationCompleted'.
  transaction & #cancellationInProgress .~ True
handleTransactionEvent transaction (TransactionCancellationCompletedTransactionEvent _) =
  -- Transition the aggregate to the terminal 'Cancelled' status and
  -- clear the transient saga-in-progress flag.
  transaction
    & #status
    .~ Cancelled
    & #cancellationInProgress
    .~ False

-- -----------------------------------------------------------------------------
-- Projection Definition
-- -----------------------------------------------------------------------------

-- | The transaction projection that rebuilds aggregate state from events.
--
-- This projection implements event sourcing by providing:
--  1. An initial seed state (transactionDefault)
--  2. An event handler that transitions between states
--
-- The projection can be used to:
--  - Rebuild current state from full event history
--  - Create snapshots at specific points in time
--  - Test state transitions independently
--  - Track transaction lifecycle
--
-- Usage with eventium:
-- >>> let events = [TransactionPostingInitiatedTransactionEvent (TransactionPostingInitiated sourceId targetId (Money 500.0) "Rent")]
-- >>> latestProjection transactionProjection events
-- Transaction {sourceAccountId = sourceId, ..., status = Pending}
--
-- Mathematical Properties:
--  - Identity: latestProjection p [] == projectionSeed p
--  - Composition: latestProjection p (e1 ++ e2) ==
--                 latestProjection p [e1, e2] (applied sequentially)
--  - Status monotonicity: Status transitions are irreversible
--    (Pending → terminal state only)
transactionProjection :: Projection Transaction TransactionEvent
transactionProjection = Projection transactionDefault handleTransactionEvent
