{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE TemplateHaskell #-}

-- |
-- Module      : Domain.Transaction.Projection
-- Description : Projection for rebuilding Transaction aggregate state from events
--
-- This module defines the Transaction aggregate state and how it is reconstructed
-- from the event stream. The projection implements event sourcing by folding
-- events over an initial state to produce the current state.
--
-- Key Components:
--   - Transaction: The aggregate state containing transfer details and status
--   - TransactionEvent: Sum type of all possible transaction events (generated by TH)
--   - transactionProjection: The projection that rebuilds state from events
--
-- The projection is the core of event sourcing - it ensures that the current
-- state can always be reconstructed by replaying the event history.
--
-- Mathematical Properties:
--   - Deterministic: Same events always produce same state
--   - Associative: Order of event application matters
--   - Idempotent event handlers: Replaying same events produces same result
--   - Status transitions: Pending → Completed | Failed (terminal states)
module Domain.Transaction.Projection
  ( -- * Transaction Aggregate
    Transaction (..),

    -- * Transaction Status
    TransactionStatus (..),

    -- * Lens Accessors
    transactionFromAccountId,
    transactionToAccountId,
    transactionAmount,
    transactionReason,
    transactionStatus,
    transactionInitiatedBy,

    -- * Event Sum Type
    TransactionEvent (..),

    -- * Projection
    transactionProjection,

    -- * Helper Functions
    transactionDefault,
  )
where

import Control.Lens (makeLenses, (&), (.~), (^.))
import Data.Aeson (FromJSON, ToJSON)
import Data.Aeson.TH (deriveJSON)
import Data.Text (Text)
import Data.UUID (nil)
import Domain.Core.Types (AccountId, Money, UserId, mkAccountId, mkMoney, unsafeUserId)
import Domain.Transaction.Events
import Eventium (Projection (..))
import GHC.Generics (Generic)
import Infrastructure.Json (unPrefixLower)
import SumTypesX.TH (SumTypeTagOptions (AppendTypeNameToTags), constructSumType, defaultSumTypeOptions, sumTypeOptionsTagOptions)

-- -----------------------------------------------------------------------------
-- Transaction Status
-- -----------------------------------------------------------------------------

-- | The status of a transaction in its lifecycle.
--
-- A transaction progresses through states:
--  - Pending: Transfer initiated but not yet completed
--  - Completed: Transfer successfully finished
--  - Failed: Transfer failed and cannot be completed
--
-- State Transitions:
--  Pending → Completed (via TransferCompleted event)
--  Pending → Failed (via TransferFailed event)
--
-- Terminal States: Completed and Failed are final states with no further transitions.
--
-- Invariant: Once a transaction reaches Completed or Failed, its status cannot change.
data TransactionStatus
  = -- | Transaction is in progress
    Pending
  | -- | Transaction completed successfully
    Completed
  | -- | Transaction failed with a reason
    Failed Text
  deriving (Show, Eq, Generic)

instance ToJSON TransactionStatus

instance FromJSON TransactionStatus

-- -----------------------------------------------------------------------------
-- Transaction Aggregate State
-- -----------------------------------------------------------------------------

-- | The Transaction aggregate state.
--
-- This represents the current state of a money transfer transaction, reconstructed
-- from its event history. The state is immutable and can only be changed by
-- applying events through the projection.
--
-- Fields:
--   - _transactionFromAccountId: Source account for the transfer
--   - _transactionToAccountId: Destination account for the transfer
--   - _transactionAmount: Amount being transferred
--   - _transactionReason: Description/reason for the transfer
--   - _transactionStatus: Current status (Pending, Completed, Failed)
--   - _transactionInitiatedBy: User who initiated the transfer (for audit trail)
--
-- Invariants:
--   - Amount is always non-negative (enforced by Money type)
--   - Status transitions are unidirectional (Pending → terminal state)
--   - Source and target accounts should be different (validated at command level)
--   - State can only be modified through event handlers
--
-- State Machine:
--   Pending -[TransferCompleted]-> Completed
--   Pending -[TransferFailed]-> Failed
--
-- Example:
-- >>> let tx = Transaction sourceId targetId (Money 500.0) "Rent" Pending userId
-- >>> tx ^. transactionStatus
-- Pending
data Transaction = Transaction
  { -- | Account from which money is being debited
    _transactionFromAccountId :: AccountId,
    -- | Account to which money is being credited
    _transactionToAccountId :: AccountId,
    -- | Amount of money being transferred
    _transactionAmount :: Money,
    -- | Reason or description for the transfer
    _transactionReason :: Text,
    -- | Current status of the transaction
    _transactionStatus :: TransactionStatus,
    -- | User who initiated the transfer
    _transactionInitiatedBy :: UserId
  }
  deriving (Show, Eq)

-- Generate lens accessors for Transaction fields
makeLenses ''Transaction

-- Derive JSON instances for Transaction
deriveJSON (unPrefixLower "_transaction") ''Transaction

-- | Default initial state for a Transaction aggregate.
--
-- This represents an uninitialized transaction before the TransferInitiated event
-- has been applied. It serves as the seed for the projection.
--
-- Note: In practice, this state should never be observed directly, as the
-- first event in any transaction stream should be TransferInitiated.
--
-- We use dummy values that will be overwritten by the first event:
--   - Empty UUIDs for account IDs and user ID (will be set by TransferInitiated)
--   - Zero amount (will be set by TransferInitiated)
--   - Empty reason (will be set by TransferInitiated)
--   - Pending status (initial status)
transactionDefault :: Transaction
transactionDefault =
  Transaction
    { _transactionFromAccountId = case mkAccountId nil of
        Right aid -> aid
        Left _ -> error "transactionDefault: mkAccountId should never fail for nil UUID",
      _transactionToAccountId = case mkAccountId nil of
        Right aid -> aid
        Left _ -> error "transactionDefault: mkAccountId should never fail for nil UUID",
      _transactionAmount = case mkMoney 0 of
        Right m -> m
        Left _ -> error "transactionDefault: mkMoney 0 should never fail",
      _transactionReason = "",
      _transactionStatus = Pending,
      _transactionInitiatedBy = unsafeUserId nil
    }

-- -----------------------------------------------------------------------------
-- Event Sum Type Construction
-- -----------------------------------------------------------------------------

-- | Generate the TransactionEvent sum type from individual event types.
--
-- This Template Haskell splice creates:
--  data TransactionEvent
--    = TransferInitiatedTransactionEvent TransferInitiated
--    | TransferCompletedTransactionEvent TransferCompleted
--    | TransferFailedTransactionEvent TransferFailed
--
-- Each variant wraps one of the individual event types defined in
-- Domain.Transaction.Events.
constructSumType
  "TransactionEvent"
  (defaultSumTypeOptions {sumTypeOptionsTagOptions = AppendTypeNameToTags})
  transactionEvents

-- Derive Show and Eq instances for the generated TransactionEvent type
deriving instance Show TransactionEvent

deriving instance Eq TransactionEvent

-- -----------------------------------------------------------------------------
-- Event Handlers
-- -----------------------------------------------------------------------------

-- | Handle an event and update the transaction state.
--
-- This function implements the business logic for how each event affects
-- the transaction state. It is pure and deterministic - the same event applied
-- to the same state always produces the same result.
--
-- Event Handling:
--  - TransferInitiated: Initialize transaction with accounts, amount, reason, and Pending status
--  - TransferCompleted: Update status to Completed (terminal state)
--  - TransferFailed: Update status to Failed with reason (terminal state)
--
-- State Transition Rules:
--  - TransferInitiated can only be applied to default/uninitialized state
--  - TransferCompleted can only be applied to Pending transactions
--  - TransferFailed can only be applied to Pending transactions
--  - No events can modify Completed or Failed transactions (idempotent)
--
-- Mathematical Property:
--  forall e1 e2 s. handleTransactionEvent (handleTransactionEvent s e1) e2
--                   == handleTransactionEvent s (e1 <> e2)
--
-- where (<>) represents event sequencing.
--
-- Note: The function is total and handles all possible events, even if they
-- represent invalid state transitions (e.g., completing an already completed
-- transaction). In such cases, the state remains unchanged (idempotent).
handleTransactionEvent :: Transaction -> TransactionEvent -> Transaction
handleTransactionEvent transaction (TransferInitiatedTransactionEvent TransferInitiated {..}) =
  -- Initialize a new transaction with transfer details
  transaction
    & transactionFromAccountId .~ transferInitiatedFromAccountId
    & transactionToAccountId .~ transferInitiatedToAccountId
    & transactionAmount .~ transferInitiatedAmount
    & transactionReason .~ transferInitiatedReason
    & transactionStatus .~ Pending
    & transactionInitiatedBy .~ transferInitiatedBy
handleTransactionEvent transaction (TransferCompletedTransactionEvent TransferCompleted) =
  -- Mark transaction as completed
  -- Only update if currently Pending (idempotent for other states)
  case transaction ^. transactionStatus of
    Pending -> transaction & transactionStatus .~ Completed
    _ -> transaction -- Already in terminal state, no change
handleTransactionEvent transaction (TransferFailedTransactionEvent TransferFailed {..}) =
  -- Mark transaction as failed with reason
  -- Only update if currently Pending (idempotent for other states)
  case transaction ^. transactionStatus of
    Pending -> transaction & transactionStatus .~ Failed transferFailedReason
    _ -> transaction -- Already in terminal state, no change

-- -----------------------------------------------------------------------------
-- Projection Definition
-- -----------------------------------------------------------------------------

-- | The transaction projection that rebuilds aggregate state from events.
--
-- This projection implements event sourcing by providing:
--  1. An initial seed state (transactionDefault)
--  2. An event handler that transitions between states
--
-- The projection can be used to:
--  - Rebuild current state from full event history
--  - Create snapshots at specific points in time
--  - Test state transitions independently
--  - Track transaction lifecycle
--
-- Usage with eventium:
-- >>> let events = [TransferInitiatedTransactionEvent (TransferInitiated sourceId targetId (Money 500.0) "Rent")]
-- >>> latestProjection transactionProjection events
-- Transaction {_transactionFromAccountId = sourceId, ..., _transactionStatus = Pending}
--
-- Mathematical Properties:
--  - Identity: latestProjection p [] == projectionSeed p
--  - Composition: latestProjection p (e1 ++ e2) ==
--                 latestProjection p [e1, e2] (applied sequentially)
--  - Status monotonicity: Status transitions are irreversible
--    (Pending → terminal state only)
transactionProjection :: Projection Transaction TransactionEvent
transactionProjection = Projection transactionDefault handleTransactionEvent
