{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE TemplateHaskell #-}

-- |
-- Module      : Domain.Account.CommandHandler
-- Description : Command handler for the Account aggregate
--
-- This module implements the command handler that validates account commands
-- against the current aggregate state and emits appropriate events.
--
-- The command handler is the core of the write side in CQRS:
--   1. Receives a command (user intent)
--   2. Loads current state via projection
--   3. Validates command against business rules
--   4. Emits events if valid (or no events if invalid)
--
-- Key Components:
--   - AccountCommand: Sum type of all account commands (generated by TH)
--   - handleAccountCommand: Command validation logic
--   - accountCommandHandler: CommandHandler for eventium integration
--
-- Business Rules Enforced:
--   - CreateAccount: Cannot create account if already exists
--   - ShareAccount: Only Owner can share, External accounts cannot be shared
--   - RevokeAccountAccess: Only Owner can revoke, Owner cannot be removed
--   - DebitAccount: Regular accounts need sufficient funds, External always succeeds
--   - CreditAccount: Always succeeds (adding money never fails)
--
-- DebitAccount and CreditAccount are internal commands issued exclusively by the
-- TransferManager process manager. They are not exposed via any API endpoint.
--
-- All validation is pure and deterministic - same command + state = same events.
module Domain.Account.CommandHandler
  ( -- * Command Sum Type
    AccountCommand (..),

    -- * Command Errors
    AccountError (..),

    -- * Command Handler
    accountCommandHandler,

    -- * Handler Function (exported for testing)
    handleAccountCommand,
  )
where

import Control.Lens ((^.))
import qualified Data.Text as T
import Domain.Account.Commands
import Domain.Account.Events
import Domain.Account.Projection
import Domain.Core.Types (AccountAccess (..), AccountRole (..), AccountType (..), Money, subtractMoney)
import Eventium (CommandHandler (..))
import SumTypesX.TH (SumTypeTagOptions (AppendTypeNameToTags), constructSumType, defaultSumTypeOptions, sumTypeOptionsTagOptions)

-- -----------------------------------------------------------------------------
-- Command Errors
-- -----------------------------------------------------------------------------

-- | Errors that can occur when handling account commands.
--
-- These are pure domain rejection reasons without contextual data.
-- The service layer maps these to richer 'Domain.Account.Errors.AccountError'
-- values with account IDs, balances, etc.
data AccountError
  = AccountAlreadyExists
  | AccountNameEmpty
  | AccountDoesNotExist
  | ExternalAccountCannotBeShared
  | NotAccountOwner
  | CannotShareWithSelf
  | CannotRevokeOwner
  | UserHasNoAccess
  | InsufficientFunds
  deriving (Show, Eq)

-- -----------------------------------------------------------------------------
-- Command Sum Type Construction
-- -----------------------------------------------------------------------------

-- | Generate the AccountCommand sum type from individual command types.
--
-- This Template Haskell splice creates:
--   data AccountCommand
--     = CreateAccountAccountCommand CreateAccount
--     | ShareAccountAccountCommand ShareAccount
--     | RevokeAccountAccessAccountCommand RevokeAccountAccess
--     | DebitAccountAccountCommand DebitAccount
--     | CreditAccountAccountCommand CreditAccount
--
-- Each variant wraps one of the individual command types defined in
-- Domain.Account.Commands.
--
-- The sum type enables pattern matching on all possible commands in the
-- handler function.
constructSumType
  "AccountCommand"
  (defaultSumTypeOptions {sumTypeOptionsTagOptions = AppendTypeNameToTags})
  accountCommands

-- -----------------------------------------------------------------------------
-- Command Handler Function
-- -----------------------------------------------------------------------------

-- | Handle an account command and produce events.
--
-- This function implements the business logic for validating commands against
-- the current aggregate state. It is pure and deterministic.
--
-- Command Handling:
--   - CreateAccount: Validates account doesn't exist, creates account with owner
--   - ShareAccount: Validates Owner role, grants access
--   - RevokeAccountAccess: Validates Owner role, revokes access
--   - DebitAccount: Validates sufficient funds, emits AccountDebited or AccountDebitRejected
--   - CreditAccount: Always succeeds, emits AccountCredited
--
-- Business Rules:
--   1. Cannot create account if already exists (name is not empty)
--   2. Cannot create account with empty name
--   3. Only Owner can share or revoke access
--   4. External accounts cannot be shared
--   5. Owner cannot be removed from access list
--   6. Regular accounts need sufficient funds for debit
--   7. External accounts can go negative (debit always succeeds)
--   8. Credit always succeeds (adding money never fails)
--
-- Returns:
--   @'Right' events@ on success, @'Left' error@ on rejection.
--
-- Mathematical Property:
--   handleAccountCommand is deterministic:
--   ∀ s c. handleAccountCommand s c == handleAccountCommand s c
handleAccountCommand :: Account -> AccountCommand -> Either AccountError [AccountEvent]
-- Handle CreateAccount command
handleAccountCommand account (CreateAccountAccountCommand CreateAccount {..})
  | not (T.null (account ^. accountName)) = Left AccountAlreadyExists
  | T.null createAccountName = Left AccountNameEmpty
  | otherwise =
      Right
        [ AccountCreatedAccountEvent
            AccountCreated
              { accountCreatedName = createAccountName,
                accountCreatedInitialBalance = createAccountInitialBalance,
                accountCreatedBy = createAccountCreatedBy,
                accountCreatedType = createAccountType
              }
        ]
-- Handle ShareAccount command
handleAccountCommand account (ShareAccountAccountCommand ShareAccount {..})
  | T.null (account ^. accountName) = Left AccountDoesNotExist
  | account ^. accountType == ExternalAccount = Left ExternalAccountCannotBeShared
  | not (isOwner shareAccountGrantedBy account) = Left NotAccountOwner
  | shareAccountUserId == shareAccountGrantedBy = Left CannotShareWithSelf
  | otherwise =
      Right
        [ AccountAccessGrantedAccountEvent
            AccountAccessGranted
              { accountAccessGrantedUserId = shareAccountUserId,
                accountAccessGrantedRole = shareAccountRole,
                accountAccessGrantedBy = shareAccountGrantedBy
              }
        ]
-- Handle RevokeAccountAccess command
handleAccountCommand account (RevokeAccountAccessAccountCommand RevokeAccountAccess {..})
  | T.null (account ^. accountName) = Left AccountDoesNotExist
  | not (isOwner revokeAccountAccessRevokedBy account) = Left NotAccountOwner
  | isOwner revokeAccountAccessUserId account = Left CannotRevokeOwner
  | not (hasAccess revokeAccountAccessUserId account) = Left UserHasNoAccess
  | otherwise =
      Right
        [ AccountAccessRevokedAccountEvent
            AccountAccessRevoked
              { accountAccessRevokedUserId = revokeAccountAccessUserId,
                accountAccessRevokedBy = revokeAccountAccessRevokedBy
              }
        ]
-- Handle DebitAccount command (internal, issued by TransferManager saga)
handleAccountCommand account (DebitAccountAccountCommand DebitAccount {..})
  | T.null (account ^. accountName) = Left AccountDoesNotExist
  | account ^. accountType == ExternalAccount =
      Right
        [ AccountDebitedAccountEvent
            AccountDebited
              { accountDebitedAmount = debitAccountAmount,
                accountDebitedTransactionId = debitAccountTransactionId,
                accountDebitedReason = debitAccountReason
              }
        ]
  | otherwise =
      case subtractMoney (account ^. accountBalance) debitAccountAmount of
        Right _ ->
          Right
            [ AccountDebitedAccountEvent
                AccountDebited
                  { accountDebitedAmount = debitAccountAmount,
                    accountDebitedTransactionId = debitAccountTransactionId,
                    accountDebitedReason = debitAccountReason
                  }
            ]
        Left _ -> Left InsufficientFunds
-- Handle CreditAccount command (internal, issued by TransferManager saga)
handleAccountCommand account (CreditAccountAccountCommand CreditAccount {..})
  | T.null (account ^. accountName) = Left AccountDoesNotExist
  | otherwise =
      Right
        [ AccountCreditedAccountEvent
            AccountCredited
              { accountCreditedAmount = creditAccountAmount,
                accountCreditedTransactionId = creditAccountTransactionId,
                accountCreditedReason = creditAccountReason
              }
        ]

-- -----------------------------------------------------------------------------
-- Command Handler
-- -----------------------------------------------------------------------------

-- | The account command handler for eventium integration.
--
-- This combines the command handler function with the account projection,
-- creating a complete CommandHandler that can be registered with eventium's
-- event store.
--
-- The CommandHandler type provides:
--   - commandHandlerHandler: The validation function (handleAccountCommand)
--   - commandHandlerProjection: How to rebuild state (accountProjection)
--
-- Usage with eventium:
-- >>> applyCommandHandler writer reader accountCommandHandler accountId command
--
-- The command handler will:
--   1. Load current state via accountProjection
--   2. Validate command via handleAccountCommand
--   3. Store emitted events in event store
--   4. Return the events that were stored
--
-- Properties:
--   - Deterministic: Same command + state = same events
--   - Pure: No side effects in validation logic
--   - Composable: Can be combined with other command handlers
accountCommandHandler :: CommandHandler Account AccountEvent AccountCommand AccountError
accountCommandHandler = CommandHandler handleAccountCommand accountProjection
