{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE TemplateHaskell #-}

-- |
-- Module      : Domain.Account.Projection
-- Description : Projection for rebuilding Account aggregate state from events
--
-- This module defines the Account aggregate state and how it is reconstructed
-- from the event stream. The projection implements event sourcing by folding
-- events over an initial state to produce the current state.
--
-- Key Components:
--   - Account: The aggregate state containing balance, name, owner, type, and access list
--   - AccountEvent: Sum type of all possible account events (generated by TH)
--   - accountProjection: The projection that rebuilds state from events
--
-- The projection is the core of event sourcing - it ensures that the current
-- state can always be reconstructed by replaying the event history.
--
-- Mathematical Properties:
--   - Deterministic: Same events always produce same state
--   - Associative: Order of event application matters
--   - Idempotent event handlers: Replaying same events produces same result
module Domain.Account.Projection
  ( -- * Account Aggregate
    Account (..),

    -- * Lens Accessors
    accountBalance,
    accountName,
    accountCreatedBy,
    accountType,
    accountAccessList,

    -- * Event Sum Type
    AccountEvent (..),

    -- * Projection
    accountProjection,

    -- * Helper Functions
    accountDefault,
    isOwner,
    hasAccess,
    getUserRole,
    canModify,
    canManage,
  )
where

import Control.Lens (makeLenses, (%~), (&), (.~), (^.))
import Data.Aeson.TH (deriveJSON)
import Data.Text (Text)
import qualified Data.UUID as UUID
import Domain.Account.Events
  ( AccountAccessGranted (..),
    AccountAccessRevoked (..),
    AccountCreated (AccountCreated),
    AccountCredited (..),
    AccountDebited (..),
    accountEvents,
  )
import qualified Domain.Account.Events as Events
import Domain.Core.Types
  ( AccountAccess (..),
    AccountRole (..),
    AccountType (..),
    Money,
    UserId,
    addMoney,
    mkMoney,
    subtractMoneyAllowNegative,
    unsafeUserId,
  )
import Eventium (Projection (..))
import Infrastructure.Json (unPrefixLower)
import SumTypesX.TH (SumTypeTagOptions (..), constructSumType, defaultSumTypeOptions, sumTypeOptionsTagOptions)

-- -----------------------------------------------------------------------------
-- Account Aggregate State
-- -----------------------------------------------------------------------------

-- | The Account aggregate state.
--
-- This represents the current state of an account, reconstructed from its
-- event history. The state is immutable and can only be changed by applying
-- events through the projection.
--
-- Fields:
--   - _accountBalance: Current account balance
--   - _accountName: Human-readable name for the account
--   - _accountCreatedBy: User who created the account (Owner)
--   - _accountType: Regular or External account
--   - _accountAccessList: List of users with access and their roles
--
-- Invariants:
--   - Regular account balance is always non-negative
--   - External account balance can be negative (representing spent money)
--   - Name is never empty for created accounts
--   - Owner is always in access list with Owner role
--   - State can only be modified through event handlers
--
-- Example:
-- >>> let account = Account (Money 1000.0) "Checking" userId RegularAccount [AccountAccess userId Owner]
-- >>> account ^. accountBalance
-- Money 1000.0
data Account = Account
  { -- | Current balance of the account
    _accountBalance :: Money,
    -- | Name of the account
    _accountName :: Text,
    -- | User who created the account
    _accountCreatedBy :: UserId,
    -- | Type of account (Regular or External)
    _accountType :: AccountType,
    -- | List of users with access and their roles
    _accountAccessList :: [AccountAccess]
  }
  deriving (Show, Eq)

-- Generate lens accessors for Account fields
makeLenses ''Account

-- Derive JSON instances for Account
deriveJSON (unPrefixLower "_account") ''Account

-- | Default initial state for an Account aggregate.
--
-- This represents an uninitialized account before the AccountCreated event
-- has been applied. It serves as the seed for the projection.
--
-- Note: In practice, this state should never be observed directly, as the
-- first event in any account stream should be AccountCreated.
accountDefault :: Account
accountDefault = case mkMoney 0 of
  Right m ->
    Account
      { _accountBalance = m,
        _accountName = "",
        _accountCreatedBy = unsafeUserId UUID.nil,
        _accountType = RegularAccount,
        _accountAccessList = []
      }
  Left _ -> error "accountDefault: mkMoney 0 should never fail"

-- | Check if a user is the owner of the account.
isOwner :: UserId -> Account -> Bool
isOwner userId account = _accountCreatedBy account == userId

-- | Check if a user has any access to the account.
hasAccess :: UserId -> Account -> Bool
hasAccess userId account =
  any (\access -> accessUserId access == userId) (_accountAccessList account)

-- | Get a user's role on the account, if any.
getUserRole :: UserId -> Account -> Maybe AccountRole
getUserRole userId account =
  accessRole <$> findAccess userId (_accountAccessList account)
  where
    findAccess uid = foldr (\a acc -> if accessUserId a == uid then Just a else acc) Nothing

-- | Check if a user can modify the account (Editor or Owner role).
canModify :: UserId -> Account -> Bool
canModify userId account =
  case getUserRole userId account of
    Just Owner -> True
    Just Editor -> True
    _ -> False

-- | Check if a user can manage the account (Owner only).
canManage :: UserId -> Account -> Bool
canManage userId account =
  case getUserRole userId account of
    Just Owner -> True
    _ -> False

-- -----------------------------------------------------------------------------
-- Event Sum Type Construction
-- -----------------------------------------------------------------------------

-- | Generate the AccountEvent sum type from individual event types.
--
-- This Template Haskell splice creates:
--   data AccountEvent
--     = AccountCreatedAccountEvent AccountCreated
--     | AccountAccessGrantedAccountEvent AccountAccessGranted
--     | AccountAccessRevokedAccountEvent AccountAccessRevoked
--     | AccountDebitedAccountEvent AccountDebited
--     | AccountCreditedAccountEvent AccountCredited
--     | AccountDebitRejectedAccountEvent AccountDebitRejected
--
-- Each variant wraps one of the individual event types defined in
-- Domain.Account.Events.
constructSumType
  "AccountEvent"
  (defaultSumTypeOptions {sumTypeOptionsTagOptions = AppendTypeNameToTags})
  accountEvents

-- Derive Show and Eq instances for the generated AccountEvent type
deriving instance Show AccountEvent

deriving instance Eq AccountEvent

-- -----------------------------------------------------------------------------
-- Event Handlers
-- -----------------------------------------------------------------------------

-- | Handle an event and update the account state.
--
-- This function implements the business logic for how each event affects
-- the account state. It is pure and deterministic - the same event applied
-- to the same state always produces the same result.
--
-- Event Handling:
--   - AccountCreated: Initialize account with name, balance, owner, type, and initial access
--   - AccountAccessGranted: Add or update user access in the access list
--   - AccountAccessRevoked: Remove user from access list
--   - AccountDebited: Subtract amount from balance (debit succeeded)
--   - AccountCredited: Add amount to balance (credit succeeded)
--   - AccountDebitRejected: No state change (informational for the saga)
handleAccountEvent :: Account -> AccountEvent -> Account
handleAccountEvent account (AccountCreatedAccountEvent created) =
  -- Initialize a new account with name, balance, owner, and type
  -- Creator automatically gets Owner role in access list
  let ownerId = Events.accountCreatedBy created
   in account
        & accountName .~ Events.accountCreatedName created
        & accountBalance .~ Events.accountCreatedInitialBalance created
        & accountCreatedBy .~ ownerId
        & accountType .~ Events.accountCreatedType created
        & accountAccessList .~ [AccountAccess ownerId Owner]
handleAccountEvent account (AccountAccessGrantedAccountEvent AccountAccessGranted {..}) =
  -- Add or update user access in the access list
  -- If user already has access, replace their role
  let existingList = _accountAccessList account
      withoutUser = filter (\a -> accessUserId a /= accountAccessGrantedUserId) existingList
      newAccess = AccountAccess accountAccessGrantedUserId accountAccessGrantedRole
   in account & accountAccessList .~ (newAccess : withoutUser)
handleAccountEvent account (AccountAccessRevokedAccountEvent AccountAccessRevoked {..}) =
  -- Remove user from access list
  let existingList = _accountAccessList account
      withoutUser = filter (\a -> accessUserId a /= accountAccessRevokedUserId) existingList
   in account & accountAccessList .~ withoutUser
handleAccountEvent account (AccountDebitedAccountEvent AccountDebited {..}) =
  -- Subtract the debited amount from balance.
  -- The command handler already validated sufficiency, so we use
  -- subtractMoneyAllowNegative which handles External accounts too.
  let newBalance = subtractMoneyAllowNegative (account ^. accountBalance) accountDebitedAmount
   in account & accountBalance .~ newBalance
handleAccountEvent account (AccountCreditedAccountEvent AccountCredited {..}) =
  -- Add the credited amount to balance. Credits always succeed.
  let newBalance = addMoney (account ^. accountBalance) accountCreditedAmount
   in account & accountBalance .~ newBalance

-- -----------------------------------------------------------------------------
-- Projection Definition
-- -----------------------------------------------------------------------------

-- | The account projection that rebuilds aggregate state from events.
--
-- This projection implements event sourcing by providing:
--   1. An initial seed state (accountDefault)
--   2. An event handler that transitions between states
--
-- The projection can be used to:
--   - Rebuild current state from full event history
--   - Create snapshots at specific points in time
--   - Test state transitions independently
--
-- Usage with eventium:
-- >>> let events = [AccountCreatedAccountEvent (AccountCreated "Savings" (Money 1000.0) userId RegularAccount)]
-- >>> latestProjection accountProjection events
-- Account {_accountBalance = Money 1000.0, _accountName = "Savings", ...}
--
-- Mathematical Properties:
--   - Identity: latestProjection p [] == projectionSeed p
--   - Composition: latestProjection p (e1 ++ e2) ==
--                  latestProjection p [e1, e2] (applied sequentially)
accountProjection :: Projection Account AccountEvent
accountProjection = Projection accountDefault handleAccountEvent
