{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE TemplateHaskell #-}

-- |
-- Module      : Domain.Account.Projection
-- Description : Projection for rebuilding Account aggregate state from events
--
-- This module defines the Account aggregate state and how it is reconstructed
-- from the event stream. The projection implements event sourcing by folding
-- events over an initial state to produce the current state.
--
-- Key Components:
--   - Account: The aggregate state containing balance, name, owner, type, and access list
--   - AccountEvent: Sum type of all possible account events (generated by TH)
--   - accountProjection: The projection that rebuilds state from events
--
-- The projection is the core of event sourcing - it ensures that the current
-- state can always be reconstructed by replaying the event history.
--
-- Mathematical Properties:
--   - Deterministic: Same events always produce same state
--   - Associative: Order of event application matters
--   - Idempotent event handlers: Replaying same events produces same result
module Domain.Account.Projection
  ( -- * Account Aggregate
    Account (..),

    -- * Optics Labels (via OverloadedLabels)
    -- $labels

    -- * Event Sum Type
    AccountEvent (..),

    -- * Projection
    accountProjection,

    -- * Helper Functions
    accountDefault,
    isOwner,
    hasAccess,
    getUserRole,
    canModify,
    canManage,
  )
where

import Data.Aeson.TH (defaultOptions, deriveJSON)
import Data.Text (Text)
import qualified Data.UUID as UUID
import Domain.Account.Events
  ( AccountAccessGranted (..),
    AccountAccessRevoked (..),
    AccountCreated (..),
    AccountCredited (..),
    AccountDebited (..),
    AccountTypeSet (..),
    OverdraftLimitSet (..),
    accountEvents,
  )
import Domain.Core.Types
  ( AccountAccess (..),
    AccountCategory (..),
    AccountRole (..),
    AccountType,
    Money,
    UserId,
    addMoney,
    defaultCash,
    mkDefaultMoney,
    subtractMoney,
    unsafeUserId,
  )
import Eventium (Projection (..))
import Eventium.TH.SumType (SumTypeTagOptions (..), constructSumType, defaultSumTypeOptions, withTagOptions)
import Optics (makeFieldLabelsNoPrefix, (&), (.~), (^.))

-- -----------------------------------------------------------------------------
-- Account Aggregate State
-- -----------------------------------------------------------------------------

-- | The Account aggregate state.
--
-- This represents the current state of an account, reconstructed from its
-- event history. The state is immutable and can only be changed by applying
-- events through the projection.
--
-- Fields:
--   - balance: Current account balance
--   - name: Human-readable name for the account
--   - createdBy: User who created the account (Owner)
--   - accountType: Regular or External account
--   - accessList: List of users with access and their roles
--
-- Invariants:
--   - Balance can be negative; overdraft enforcement is at the account level via overdraftLimit
--   - Regular accounts default to overdraftLimit = Just 0 (no overdraft)
--   - External accounts default to overdraftLimit = Nothing (unlimited)
--   - Name is never empty for created accounts
--   - Owner is always in access list with Owner role
--   - State can only be modified through event handlers
--
-- Example:
-- >>> let account = Account (Money 1000.0) "Checking" userId RegularAccount [AccountAccess userId Owner]
-- >>> account ^. #balance
-- Money 1000.0
data Account = Account
  { -- | Current balance of the account
    balance :: Money,
    -- | Name of the account
    name :: Text,
    -- | User who created the account
    createdBy :: UserId,
    -- | Account category (Regular with type, or External)
    accountCategory :: AccountCategory,
    -- | List of users with access and their roles
    accessList :: [AccountAccess],
    -- | Overdraft limit. Nothing = unlimited, Just limit = max negative balance
    overdraftLimit :: Maybe Money
  }
  deriving (Show, Eq)

-- Generate optics labels for Account fields (accessed via #fieldName)
makeFieldLabelsNoPrefix ''Account

-- Derive JSON instances for Account (fields already unprefixed)
deriveJSON defaultOptions ''Account

-- | Default initial state for an Account aggregate.
--
-- This represents an uninitialized account before the AccountCreated event
-- has been applied. It serves as the seed for the projection.
--
-- Note: In practice, this state should never be observed directly, as the
-- first event in any account stream should be AccountCreated.
accountDefault :: Account
accountDefault = case mkDefaultMoney 0 of
  Right m ->
    Account
      { balance = m,
        name = "",
        createdBy = unsafeUserId UUID.nil,
        accountCategory = Regular defaultCash,
        accessList = [],
        overdraftLimit = Just m
      }
  Left _ -> error "accountDefault: mkDefaultMoney 0 should never fail"

-- | Check if a user is the owner of the account.
isOwner :: UserId -> Account -> Bool
isOwner uid account = account.createdBy == uid

-- | Check if a user has any access to the account.
hasAccess :: UserId -> Account -> Bool
hasAccess uid account =
  any (\a -> a.userId == uid) (account ^. #accessList)

-- | Get a user's role on the account, if any.
getUserRole :: UserId -> Account -> Maybe AccountRole
getUserRole uid account =
  (.role) <$> findAccess uid (account ^. #accessList)
  where
    findAccess theUid = foldr (\a acc -> if a.userId == theUid then Just a else acc) Nothing

-- | Check if a user can modify the account (Editor or Owner role).
canModify :: UserId -> Account -> Bool
canModify uid account =
  case getUserRole uid account of
    Just Owner -> True
    Just Editor -> True
    _ -> False

-- | Check if a user can manage the account (Owner only).
canManage :: UserId -> Account -> Bool
canManage uid account =
  case getUserRole uid account of
    Just Owner -> True
    _ -> False

-- -----------------------------------------------------------------------------
-- Event Sum Type Construction
-- -----------------------------------------------------------------------------

-- | Generate the AccountEvent sum type from individual event types.
--
-- This Template Haskell splice creates:
--   data AccountEvent
--     = AccountCreatedAccountEvent AccountCreated
--     | AccountAccessGrantedAccountEvent AccountAccessGranted
--     | AccountAccessRevokedAccountEvent AccountAccessRevoked
--     | AccountDebitedAccountEvent AccountDebited
--     | AccountCreditedAccountEvent AccountCredited
--     | AccountDebitRejectedAccountEvent AccountDebitRejected
--
-- Each variant wraps one of the individual event types defined in
-- Domain.Account.Events.
constructSumType
  "AccountEvent"
  (withTagOptions AppendTypeNameToTags defaultSumTypeOptions)
  accountEvents

-- Derive Show and Eq instances for the generated AccountEvent type
deriving instance Show AccountEvent

deriving instance Eq AccountEvent

-- -----------------------------------------------------------------------------
-- Event Handlers
-- -----------------------------------------------------------------------------

-- | Handle an event and update the account state.
--
-- This function implements the business logic for how each event affects
-- the account state. It is pure and deterministic - the same event applied
-- to the same state always produces the same result.
--
-- Event Handling:
--   - AccountCreated: Initialize account with name, balance, owner, type, and initial access
--   - AccountAccessGranted: Add or update user access in the access list
--   - AccountAccessRevoked: Remove user from access list
--   - AccountDebited: Subtract amount from balance (debit succeeded)
--   - AccountCredited: Add amount to balance (credit succeeded)
--   - AccountDebitRejected: No state change (informational for the saga)
handleAccountEvent :: Account -> AccountEvent -> Account
handleAccountEvent account (AccountCreatedAccountEvent created) =
  -- Initialize a new account with name, balance, owner, and type
  -- Creator automatically gets Owner role in access list
  let ownerId = created.by
   in account
        & #name
        .~ created.name
        & #balance
        .~ created.initialBalance
        & #createdBy
        .~ ownerId
        & #accountCategory
        .~ created.accountCategory
        & #accessList
        .~ [AccountAccess ownerId Owner]
        & #overdraftLimit
        .~ created.overdraftLimit
handleAccountEvent account (AccountAccessGrantedAccountEvent AccountAccessGranted {..}) =
  -- Add or update user access in the access list
  -- If user already has access, replace their role
  let existingList = account ^. #accessList
      withoutUser = filter (\a -> a.userId /= userId) existingList
      newAccess = AccountAccess userId role
   in account & #accessList .~ (newAccess : withoutUser)
handleAccountEvent account (AccountAccessRevokedAccountEvent AccountAccessRevoked {..}) =
  -- Remove user from access list
  let existingList = account ^. #accessList
      withoutUser = filter (\a -> a.userId /= userId) existingList
   in account & #accessList .~ withoutUser
handleAccountEvent account (AccountDebitedAccountEvent AccountDebited {..}) =
  -- Subtract the debited amount from balance.
  -- The command handler already validated currency match; subtractMoney allows negative results
  -- (overdraft enforcement is at account level).
  case subtractMoney (account ^. #balance) amount of
    Right newBalance -> account & #balance .~ newBalance
    Left _ -> account -- Impossible: currency was validated by command handler
handleAccountEvent account (AccountCreditedAccountEvent AccountCredited {..}) =
  -- Add the credited amount to balance. Credits always succeed (currency validated by command handler).
  case addMoney (account ^. #balance) amount of
    Right newBalance -> account & #balance .~ newBalance
    Left _ -> account -- Impossible: currency was validated by command handler
handleAccountEvent account (OverdraftLimitSetAccountEvent OverdraftLimitSet {..}) =
  account & #overdraftLimit .~ overdraftLimit
handleAccountEvent account (AccountTypeSetAccountEvent AccountTypeSet {..}) =
  account & #accountCategory .~ Regular accountType

-- -----------------------------------------------------------------------------
-- Projection Definition
-- -----------------------------------------------------------------------------

-- | The account projection that rebuilds aggregate state from events.
--
-- This projection implements event sourcing by providing:
--   1. An initial seed state (accountDefault)
--   2. An event handler that transitions between states
--
-- The projection can be used to:
--   - Rebuild current state from full event history
--   - Create snapshots at specific points in time
--   - Test state transitions independently
--
-- Usage with eventium:
-- >>> let events = [AccountCreatedAccountEvent (AccountCreated "Savings" (Money 1000.0) userId RegularAccount)]
-- >>> latestProjection accountProjection events
-- Account {balance = Money 1000.0, name = "Savings", ...}
--
-- Mathematical Properties:
--   - Identity: latestProjection p [] == projectionSeed p
--   - Composition: latestProjection p (e1 ++ e2) ==
--                  latestProjection p [e1, e2] (applied sequentially)
accountProjection :: Projection Account AccountEvent
accountProjection = Projection accountDefault handleAccountEvent
