{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE TemplateHaskell #-}

-- |
-- Module      : Domain.User.CommandHandler
-- Description : Command handler for the User aggregate
--
-- This module implements the command handler that validates user commands
-- against the current aggregate state and emits appropriate events.
--
-- The command handler is the core of the write side in CQRS:
--   1. Receives a command (user intent)
--   2. Loads current state via projection
--   3. Validates command against business rules
--   4. Emits events if valid (or no events if invalid)
--
-- Key Components:
--   - UserCommand: Sum type of all user commands (generated by TH)
--   - handleUserCommand: Command validation logic
--   - userCommandHandler: CommandHandler for eventium integration
--
-- Business Rules Enforced:
--   - RegisterUser: Cannot register if user already exists
--   - RegisterViaTelegram: Cannot register if user already exists
--   - LinkOAuthAccount: User must exist, OAuth not already linked
--   - LinkTelegramAccount: User must exist, Telegram not already linked
--   - UnlinkOAuthAccount: User must exist, must have other login methods
--   - UnlinkTelegramAccount: User must exist, must have other login methods
--   - ChangePassword: User must exist
--
-- All validation is pure and deterministic - same command + state = same events.
module Domain.User.CommandHandler
  ( -- * Command Sum Type
    UserCommand (..),

    -- * Command Errors
    UserError (..),

    -- * Command Handler
    userCommandHandler,

    -- * Handler Function (exported for testing)
    handleUserCommand,
  )
where

import Domain.Core.Types
  ( OAuthIdentity (..),
  )
import Domain.User.Commands
import Domain.User.Events
import Domain.User.Projection
import Eventium (CommandHandler (..))
import SumTypesX.TH (SumTypeTagOptions (AppendTypeNameToTags), constructSumType, defaultSumTypeOptions, sumTypeOptionsTagOptions)

-- -----------------------------------------------------------------------------
-- Command Errors
-- -----------------------------------------------------------------------------

-- | Errors that can occur when handling user commands.
data UserError
  = UserAlreadyRegistered
  | UserNotRegistered
  | OAuthAlreadyLinked
  | TelegramAlreadyLinked
  | CannotRemoveLastLoginMethod
  | OAuthNotLinked
  | TelegramNotLinked
  deriving (Show, Eq)

-- -----------------------------------------------------------------------------
-- Command Sum Type Construction
-- -----------------------------------------------------------------------------

-- | Generate the UserCommand sum type from individual command types.
--
-- This Template Haskell splice creates:
--   data UserCommand
--     = RegisterUserUserCommand RegisterUser
--     | RegisterViaTelegramUserCommand RegisterViaTelegram
--     | LinkOAuthAccountUserCommand LinkOAuthAccount
--     | LinkTelegramAccountUserCommand LinkTelegramAccount
--     | UnlinkOAuthAccountUserCommand UnlinkOAuthAccount
--     | UnlinkTelegramAccountUserCommand UnlinkTelegramAccount
--     | ChangePasswordUserCommand ChangePassword
--
-- Each variant wraps one of the individual command types defined in
-- Domain.User.Commands.
constructSumType
  "UserCommand"
  (defaultSumTypeOptions {sumTypeOptionsTagOptions = AppendTypeNameToTags})
  userCommands

-- -----------------------------------------------------------------------------
-- Command Handler Function
-- -----------------------------------------------------------------------------

-- | Handle a user command and produce events.
--
-- This function implements the business logic for validating commands against
-- the current aggregate state. It is pure and deterministic.
--
-- Command Handling:
--   - RegisterUser: Validates user doesn't exist, creates user
--   - RegisterViaTelegram: Validates user doesn't exist, creates user
--   - LinkOAuthAccount: Validates user exists and OAuth not already linked
--   - LinkTelegramAccount: Validates user exists and Telegram not already linked
--   - UnlinkOAuthAccount: Validates user exists and has other login methods
--   - UnlinkTelegramAccount: Validates user exists and has other login methods
--   - ChangePassword: Validates user exists
--
-- Returns:
--   @'Right' events@ on success, @'Left' error@ on rejection.
--
-- Note: Email/Telegram uniqueness across users must be validated at the API layer
-- using read models, as the aggregate only has access to its own state.
handleUserCommand :: User -> UserCommand -> Either UserError [UserEvent]
-- Handle RegisterUser command
handleUserCommand user (RegisterUserUserCommand RegisterUser {..})
  | _userIsRegistered user = Left UserAlreadyRegistered
  | otherwise =
      Right
        [ UserRegisteredUserEvent
            UserRegistered
              { userRegisteredEmail = registerUserEmail,
                userRegisteredPasswordHash = registerUserPasswordHash,
                userRegisteredExternalAccountId = registerUserExternalAccountId
              }
        ]
-- Handle RegisterViaTelegram command
handleUserCommand user (RegisterViaTelegramUserCommand RegisterViaTelegram {..})
  | _userIsRegistered user = Left UserAlreadyRegistered
  | otherwise =
      Right
        [ UserRegisteredViaTelegramUserEvent
            UserRegisteredViaTelegram
              { userRegisteredViaTelegramIdentity = registerViaTelegramIdentity,
                userRegisteredViaTelegramExternalAccountId = registerViaTelegramExternalAccountId
              }
        ]
-- Handle LinkOAuthAccount command
handleUserCommand user (LinkOAuthAccountUserCommand LinkOAuthAccount {..})
  | not (_userIsRegistered user) = Left UserNotRegistered
  | hasOAuthProvider (oauthProvider linkOAuthAccountIdentity) (_userOAuthIdentities user) = Left OAuthAlreadyLinked
  | otherwise =
      Right
        [ OAuthAccountLinkedUserEvent
            OAuthAccountLinked
              { oAuthAccountLinkedIdentity = linkOAuthAccountIdentity
              }
        ]
  where
    hasOAuthProvider provider identities =
      any (\i -> oauthProvider i == provider) identities
-- Handle LinkTelegramAccount command
handleUserCommand user (LinkTelegramAccountUserCommand LinkTelegramAccount {..})
  | not (_userIsRegistered user) = Left UserNotRegistered
  | Just _ <- _userTelegramIdentity user = Left TelegramAlreadyLinked
  | otherwise =
      Right
        [ TelegramAccountLinkedUserEvent
            TelegramAccountLinked
              { telegramAccountLinkedIdentity = linkTelegramAccountIdentity
              }
        ]
-- Handle UnlinkOAuthAccount command
handleUserCommand user (UnlinkOAuthAccountUserCommand UnlinkOAuthAccount {..})
  | not (_userIsRegistered user) = Left UserNotRegistered
  | loginMethodCount user <= 1 = Left CannotRemoveLastLoginMethod
  | not (hasOAuthIdentity unlinkOAuthAccountIdentity (_userOAuthIdentities user)) = Left OAuthNotLinked
  | otherwise =
      Right
        [ OAuthAccountUnlinkedUserEvent
            OAuthAccountUnlinked
              { oAuthAccountUnlinkedIdentity = unlinkOAuthAccountIdentity
              }
        ]
  where
    hasOAuthIdentity target identities =
      any
        ( \i ->
            oauthProvider i == oauthProvider target
              && oauthSubject i == oauthSubject target
        )
        identities
-- Handle UnlinkTelegramAccount command
handleUserCommand user (UnlinkTelegramAccountUserCommand UnlinkTelegramAccount)
  | not (_userIsRegistered user) = Left UserNotRegistered
  | loginMethodCount user <= 1 = Left CannotRemoveLastLoginMethod
  | Nothing <- _userTelegramIdentity user = Left TelegramNotLinked
  | otherwise =
      Right [TelegramAccountUnlinkedUserEvent TelegramAccountUnlinked]
-- Handle ChangePassword command
handleUserCommand user (ChangePasswordUserCommand ChangePassword {..})
  | not (_userIsRegistered user) = Left UserNotRegistered
  | otherwise =
      Right
        [ PasswordChangedUserEvent
            PasswordChanged
              { passwordChangedNewHash = changePasswordNewHash
              }
        ]

-- -----------------------------------------------------------------------------
-- Command Handler
-- -----------------------------------------------------------------------------

-- | The user command handler for eventium integration.
--
-- This combines the command handler function with the user projection,
-- creating a complete CommandHandler that can be registered with eventium's
-- event store.
--
-- The CommandHandler type provides:
--   - commandHandlerHandler: The validation function (handleUserCommand)
--   - commandHandlerProjection: How to rebuild state (userProjection)
--
-- Usage with eventium:
-- >>> applyCommandHandler writer reader userCommandHandler userId command
--
-- The command handler will:
--   1. Load current state via userProjection
--   2. Validate command via handleUserCommand
--   3. Store emitted events in event store
--   4. Return the events that were stored
--
-- Properties:
--   - Deterministic: Same command + state = same events
--   - Pure: No side effects in validation logic
--   - Composable: Can be combined with other command handlers
userCommandHandler :: CommandHandler User UserEvent UserCommand UserError
userCommandHandler = CommandHandler handleUserCommand userProjection
