{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE TemplateHaskell #-}

-- |
-- Module      : Domain.User.Projection
-- Description : Projection for rebuilding User aggregate state from events
--
-- This module defines the User aggregate state and how it is reconstructed
-- from the event stream. The projection implements event sourcing by folding
-- events over an initial state to produce the current state.
--
-- Key Components:
--   - User: The aggregate state containing email, password, OAuth/Telegram identities
--   - UserEvent: Sum type of all possible user events (generated by TH)
--   - userProjection: The projection that rebuilds state from events
--
-- The projection is the core of event sourcing - it ensures that the current
-- state can always be reconstructed by replaying the event history.
--
-- Mathematical Properties:
--   - Deterministic: Same events always produce same state
--   - Associative: Order of event application matters
--   - Idempotent event handlers: Replaying same events produces same result
module Domain.User.Projection
  ( -- * User Aggregate
    User (..),

    -- * Lens Accessors
    userEmail,
    userPasswordHash,
    userOAuthIdentities,
    userTelegramIdentity,
    userExternalAccountId,
    userIsRegistered,

    -- * Event Sum Type
    UserEvent (..),

    -- * Projection
    userProjection,

    -- * Helper Functions
    userDefault,
    hasPassword,
    hasLoginMethod,
    loginMethodCount,
  )
where

import Control.Lens (makeLenses, (%~), (&), (.~))
import Data.Aeson.TH (deriveJSON)
import Data.Text (Text)
import qualified Data.UUID as UUID
import Domain.Core.Types
  ( AccountId,
    OAuthIdentity (..),
    OAuthProvider,
    PasswordHash,
    TelegramIdentity,
    unsafeAccountId,
  )
import Domain.User.Events
import Eventium (Projection (..))
import Eventium.Json (unPrefixLower)
import SumTypesX.TH (SumTypeTagOptions (..), constructSumType, defaultSumTypeOptions, sumTypeOptionsTagOptions)

-- -----------------------------------------------------------------------------
-- User Aggregate State
-- -----------------------------------------------------------------------------

-- | The User aggregate state.
--
-- This represents the current state of a user, reconstructed from its
-- event history. The state is immutable and can only be changed by applying
-- events through the projection.
--
-- Fields:
--   - _userEmail: User's email address (primary identifier for web login)
--   - _userPasswordHash: Optional password hash (None for Telegram-only users)
--   - _userOAuthIdentities: List of linked OAuth identities
--   - _userTelegramIdentity: Optional linked Telegram identity
--   - _userExternalAccountId: Reference to auto-created External account
--   - _userIsRegistered: Whether the user has been registered (vs default state)
--
-- Invariants:
--   - User must have at least one login method (password, OAuth, or Telegram)
--   - Email is unique across all users (enforced at API layer via read model)
--   - Telegram ID is unique across all users (enforced at API layer via read model)
--   - OAuth identities are unique across all users (enforced at API layer via read model)
--
-- Example:
-- >>> let user = User "user@example.com" (Just hash) [] Nothing extAccId True
-- >>> user ^. userEmail
-- "user@example.com"
data User = User
  { -- | User's email address (primary identifier for web login)
    _userEmail :: Text,
    -- | Optional password hash (Argon2)
    _userPasswordHash :: Maybe PasswordHash,
    -- | List of linked OAuth identities
    _userOAuthIdentities :: [OAuthIdentity],
    -- | Optional linked Telegram identity
    _userTelegramIdentity :: Maybe TelegramIdentity,
    -- | Reference to auto-created External account
    _userExternalAccountId :: AccountId,
    -- | Whether this user has been registered
    _userIsRegistered :: Bool
  }
  deriving (Show, Eq)

-- Generate lens accessors for User fields
makeLenses ''User

-- Derive JSON instances for User
deriveJSON (unPrefixLower "_user") ''User

-- | Default initial state for a User aggregate.
--
-- This represents an uninitialized user before the UserRegistered event
-- has been applied. It serves as the seed for the projection.
--
-- Note: In practice, this state should never be observed directly, as the
-- first event in any user stream should be UserRegistered or UserRegisteredViaTelegram.
userDefault :: User
userDefault =
  User
    { _userEmail = "",
      _userPasswordHash = Nothing,
      _userOAuthIdentities = [],
      _userTelegramIdentity = Nothing,
      _userExternalAccountId = unsafeAccountId UUID.nil,
      _userIsRegistered = False
    }

-- | Check if user has a password set.
hasPassword :: User -> Bool
hasPassword user = case _userPasswordHash user of
  Just _ -> True
  Nothing -> False

-- | Check if user has at least one login method.
--
-- A user must have at least one of:
-- - Password
-- - OAuth identity
-- - Telegram identity
hasLoginMethod :: User -> Bool
hasLoginMethod user = loginMethodCount user > 0

-- | Count the number of login methods a user has.
--
-- Useful for determining if an OAuth or Telegram account can be unlinked.
loginMethodCount :: User -> Int
loginMethodCount user =
  passwordCount + oauthCount + telegramCount
  where
    passwordCount = if hasPassword user then 1 else 0
    oauthCount = length (_userOAuthIdentities user)
    telegramCount = case _userTelegramIdentity user of
      Just _ -> 1
      Nothing -> 0

-- -----------------------------------------------------------------------------
-- Event Sum Type Construction
-- -----------------------------------------------------------------------------

-- | Generate the UserEvent sum type from individual event types.
--
-- This Template Haskell splice creates:
--   data UserEvent
--     = UserRegisteredUserEvent UserRegistered
--     | UserRegisteredViaTelegramUserEvent UserRegisteredViaTelegram
--     | OAuthAccountLinkedUserEvent OAuthAccountLinked
--     | TelegramAccountLinkedUserEvent TelegramAccountLinked
--     | OAuthAccountUnlinkedUserEvent OAuthAccountUnlinked
--     | TelegramAccountUnlinkedUserEvent TelegramAccountUnlinked
--     | PasswordChangedUserEvent PasswordChanged
--
-- Each variant wraps one of the individual event types defined in
-- Domain.User.Events.
constructSumType
  "UserEvent"
  (defaultSumTypeOptions {sumTypeOptionsTagOptions = AppendTypeNameToTags})
  userEvents

-- Derive Show and Eq instances for the generated UserEvent type
deriving instance Show UserEvent

deriving instance Eq UserEvent

-- -----------------------------------------------------------------------------
-- Event Handlers
-- -----------------------------------------------------------------------------

-- | Handle an event and update the user state.
--
-- This function implements the business logic for how each event affects
-- the user state. It is pure and deterministic - the same event applied
-- to the same state always produces the same result.
--
-- Event Handling:
--   - UserRegistered: Initialize user with email, password, and external account
--   - UserRegisteredViaTelegram: Initialize user with Telegram identity and external account
--   - OAuthAccountLinked: Add OAuth identity to the list
--   - TelegramAccountLinked: Set Telegram identity
--   - OAuthAccountUnlinked: Remove OAuth identity from the list
--   - TelegramAccountUnlinked: Clear Telegram identity
--   - PasswordChanged: Update password hash
handleUserEvent :: User -> UserEvent -> User
handleUserEvent user (UserRegisteredUserEvent UserRegistered {..}) =
  -- Initialize a new user with email and password
  user
    & userEmail .~ userRegisteredEmail
    & userPasswordHash .~ Just userRegisteredPasswordHash
    & userExternalAccountId .~ userRegisteredExternalAccountId
    & userIsRegistered .~ True
handleUserEvent user (UserRegisteredViaTelegramUserEvent UserRegisteredViaTelegram {..}) =
  -- Initialize a new user with Telegram identity (no password)
  user
    & userTelegramIdentity .~ Just userRegisteredViaTelegramIdentity
    & userExternalAccountId .~ userRegisteredViaTelegramExternalAccountId
    & userIsRegistered .~ True
handleUserEvent user (OAuthAccountLinkedUserEvent OAuthAccountLinked {..}) =
  -- Add OAuth identity to the list
  user
    & userOAuthIdentities %~ (oAuthAccountLinkedIdentity :)
handleUserEvent user (TelegramAccountLinkedUserEvent TelegramAccountLinked {..}) =
  -- Set Telegram identity
  user
    & userTelegramIdentity .~ Just telegramAccountLinkedIdentity
handleUserEvent user (OAuthAccountUnlinkedUserEvent OAuthAccountUnlinked {..}) =
  -- Remove OAuth identity from the list
  user
    & userOAuthIdentities %~ filter (not . matchesOAuth oAuthAccountUnlinkedIdentity)
  where
    matchesOAuth target identity =
      oauthProvider target == oauthProvider identity
        && oauthSubject target == oauthSubject identity
handleUserEvent user (TelegramAccountUnlinkedUserEvent TelegramAccountUnlinked) =
  -- Clear Telegram identity
  user
    & userTelegramIdentity .~ Nothing
handleUserEvent user (PasswordChangedUserEvent PasswordChanged {..}) =
  -- Update password hash
  user
    & userPasswordHash .~ Just passwordChangedNewHash

-- -----------------------------------------------------------------------------
-- Projection Definition
-- -----------------------------------------------------------------------------

-- | The user projection that rebuilds aggregate state from events.
--
-- This projection implements event sourcing by providing:
--   1. An initial seed state (userDefault)
--   2. An event handler that transitions between states
--
-- The projection can be used to:
--   - Rebuild current state from full event history
--   - Create snapshots at specific points in time
--   - Test state transitions independently
--
-- Usage with eventium:
-- >>> let events = [UserRegisteredUserEvent (UserRegistered "test@example.com" hash extId)]
-- >>> latestProjection userProjection events
-- User {_userEmail = "test@example.com", ...}
--
-- Mathematical Properties:
--   - Identity: latestProjection p [] == projectionSeed p
--   - Composition: latestProjection p (e1 ++ e2) ==
--                  latestProjection p [e1, e2] (applied sequentially)
userProjection :: Projection User UserEvent
userProjection = Projection userDefault handleUserEvent
